import { Download } from "lucide-react";
import { Button } from "@/components/ui/button";
import { type CalculatorValues, type CalculatorResults } from "./CalculatorSection";

const formatCurrency = (value: number): string => {
    return new Intl.NumberFormat("en-IN").format(Math.round(value));
};

interface ExportReportProps {
    values: CalculatorValues;
    results: CalculatorResults;
}

const ExportReport = ({ values, results }: ExportReportProps) => {
    const handleExport = () => {
        const reportContent = `
SIP INVESTMENT SUMMARY REPORT
Generated on: ${new Date().toLocaleDateString("en-IN")}

INVESTMENT PARAMETERS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Monthly Investment:        ₹${formatCurrency(values.monthlyInvestment)}
Expected Annual Return:    ${values.annualReturn}%
Investment Duration:       ${values.years} years

PROJECTED RESULTS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Total Amount Invested:     ₹${formatCurrency(results.totalInvested)}
Estimated Future Value:    ₹${formatCurrency(results.futureValue)}
Wealth Gained:             ₹${formatCurrency(results.wealthGained)}
Return on Investment:      ${((results.wealthGained / results.totalInvested) * 100).toFixed(2)}%

IMPORTANT DISCLAIMERS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
• This is an educational tool for illustration purposes only
• Actual returns may vary based on market conditions
• Past performance does not guarantee future results
• Consult a financial advisor before making investment decisions
• This is not financial advice or a recommendation to invest

Generated by SIP Calculator - Investor Education Tool
    `.trim();

        const blob = new Blob([reportContent], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const link = document.createElement("a");
        link.href = url;
        link.download = `SIP-Investment-Summary-${new Date().toISOString().split("T")[0]}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    };

    return (
        <Button
            onClick={handleExport}
            variant="outline"
            className="w-full gap-2 font-heading font-semibold"
        >
            <Download className="h-4 w-4" />
            Download Investment Summary
        </Button>
    );
};

export default ExportReport;
